// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUz02CS60Ps2eKNpA2Xxqj4VJBaj5AfQ',
    appId: '1:222666104358:web:dac7837d9088a912ae50e7',
    messagingSenderId: '222666104358',
    projectId: 'karlo-shopping',
    authDomain: 'karlo-shopping.firebaseapp.com',
    storageBucket: 'karlo-shopping.appspot.com',
    measurementId: 'G-D3F28X3TR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7nYknSZPYAZduy_K0_CD2P9n2Zw5Pp8',
    appId: '1:222666104358:android:65b41c7d1f3391d7ae50e7',
    messagingSenderId: '222666104358',
    projectId: 'karlo-shopping',
    storageBucket: 'karlo-shopping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsx2chimY3lmst1AjSMR6S5rolpmOiAYQ',
    appId: '1:222666104358:ios:5b74f5829be569deae50e7',
    messagingSenderId: '222666104358',
    projectId: 'karlo-shopping',
    storageBucket: 'karlo-shopping.appspot.com',
    iosClientId: '222666104358-i3t8ai4nv0uvf34tao91jur3osubg92m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
